### ISSUE TITLE
Unittest depends on response from geoserver-systest

### ISSUE THREAD

**Issue by mhidas** [aodn/data-services#529]
I just ran the data-services unittests in the PO box. This normally passes, but this time I got:
```
Executing: 'lib/test/python/test_wfs_query.py'
#############################
E
======================================================================
ERROR: test_wfs_request_matching_file_pattern (__main__.TestGenerateNetCDFAtt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/test/python/test_wfs_query.py", line 20, in test_wfs_request_matching_file_pattern
    res =  wfs_request_matching_file_pattern(self.layer, self.pattern, geoserver_url=self.geoserver_url, url_column=self.url_column, s3_bucket_url=True)[0]
  File "/vagrant/src/data-services/lib/python/util.py", line 87, in wfs_request_matching_file_pattern
    response  = wfs11.getfeature(typename=imos_layer_name, filter=filterxml)
  File "/usr/local/lib/python2.7/dist-packages/owslib/feature/wfs110.py", line 225, in getfeature
    u = openURL(base_url, data, method, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/owslib/util.py", line 186, in openURL
    **rkwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='geoserver-systest.aodn.org.au', port=80): Read timed out. (read timeout=30)

----------------------------------------------------------------------
Ran 1 test in 31.865s

FAILED (errors=1)
```

I don't think it's a good idea to have this dependence on a server that has nothing to do with anything in the data-services repo. Isn't the idea of a unittest that it tests a single, isolated *unit* of code?

**Comment by lbesnard** [comment]
> Isn't the idea of a unittest that it tests a single, isolated unit of code?

agree, but how do you make sure that a script on data-services will run perfectly, if the function related to the unittest is modified and the unittest removed ?

**Comment by mhidas** [comment]
This is not a big deal if you're running the tests manually. Seeing the reason for the failure, you can always wait a bit and re-run this test. It becomes more of an issue when we have automated processes that depend on all these tests, like the current data-services production merge Jenkins job. 

So my suggestion would just be to not include this particular test in the main test.sh file. You can still run the test yourself whenever you make a change to that code.

**Comment by lbesnard** [comment]
https://github.com/aodn/data-services/pull/530

**Comment by mhidas** [comment]
:+1:  Thanks @lbesnard
